introspection: http://localhost:8080/graphql

servers:
  - url: http://localhost:8080/graphql
    description: Local Server 

info:
    title: Lead Commerce X API
    description: Markdown enabled description of your api.    

domains:
  - name: Fetching Users
    description: Base methods to fetch users.
    usecases:
     - name: Fetch Users
       description: Query list of Users
       query: query.users
  - name: Fetching Products
    description: Base methods to fetch products.
    usecases:
     - name: Fetch Products
       description: Query list of Products
       query: query.products
       